export const DEFAULT_SKILL_LIBRARY = [
  { name: 'React', category: 'Frontend', description: 'Component-driven UI development with modern React patterns.' },
  { name: 'TypeScript', category: 'Programming', description: 'Typed JavaScript for scalable application development.' },
  { name: 'Node.js', category: 'Backend', description: 'Server-side JavaScript runtime for APIs and services.' },
  { name: 'Express', category: 'Backend', description: 'REST API and middleware development with Express.' },
  { name: 'MongoDB', category: 'Database', description: 'Document database design, queries, and modeling.' },
  { name: 'PostgreSQL', category: 'Database', description: 'Relational database design and optimization.' },
  { name: 'Tailwind CSS', category: 'Frontend', description: 'Utility-first styling for modern interfaces.' },
  { name: 'Figma', category: 'Design Tools', description: 'Interface prototyping and design system collaboration.' },
  { name: 'UI Design', category: 'Design', description: 'Visual interface design for responsive products.' },
  { name: 'UX Research', category: 'Design', description: 'User interviews, testing, and insight synthesis.' },
  { name: 'Agile Delivery', category: 'Project Management', description: 'Sprint planning and iterative delivery alignment.' },
  { name: 'QA Testing', category: 'Quality', description: 'Manual and exploratory testing of workflows.' },
  { name: 'Automation Testing', category: 'Quality', description: 'Automated test coverage for UI and API flows.' },
  { name: 'Data Analysis', category: 'Analytics', description: 'Data interpretation, reporting, and insight building.' },
  { name: 'Excel', category: 'Operations', description: 'Spreadsheet formulas, reporting, and operational planning.' },
  { name: 'Communication', category: 'Soft Skills', description: 'Clear written and verbal cross-team communication.' },
  { name: 'Leadership', category: 'Soft Skills', description: 'Mentoring, ownership, and team direction.' },
  { name: 'Recruitment', category: 'HR', description: 'Candidate sourcing, screening, and hiring coordination.' },
  { name: 'Payroll Processing', category: 'Finance', description: 'Salary reconciliation, payout validation, and payroll records.' },
  { name: 'Performance Management', category: 'HR', description: 'Goal setting, review cycles, and development planning.' },
];
